[theme]
primaryColor = "#1473E6"
backgroundColor = "#F5F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B1F33"
font = "sans-serif"

[server]
headless = true

[browser]
gatherUsageStats = false
